frame = "buttonless"
title-hidden = true
vsync = false

[font]
normal = ["MonaspiceKr Nerd Font", "D2Coding ligature"]
size = 12

[font.features]
"MonaspiceKr Nerd Font" = ["+calt", "+liga", "+dlig"]
"D2Coding ligature" = ["+calt", "+liga", "+dlig"]
