set -g default-terminal "wezterm"
set-option -sa terminal-overrides ",wezterm*:Tc"

bind s choose-tree -swZ -O name

set -g prefix C-x
unbind C-b
bind-key C-x send-prefix


unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind-key r command-prompt -p "place right of. select target window" "move-pane -h -t %%"
bind-key b command-prompt -p "place below. select target window" "move-pane -v -t %%"

unbind R
bind R source-file ~/.tmux.conf \; display "\uf135  tmux conf reloaded!"

# Open current directory
bind o run-shell "open #{pane_current_path}"

bind -r e kill-pane
bind -r m resize-pane -Z

set -g mouse on

# act like vim
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @resurrect-capture-pane-contents 'on'
# set -g @resurrect-save-confirm 'on'
# set -g @resurrect-restore-confirm 'on'

set -g @continuum-restore 'on'
set -g @continnum-save-interval '15'

set -g @dracula-plugins "battery network continuum"

set -g @dracula-refresh-rate 1
set -g @dracula-show-timezone true
set -g @dracula-show-powerline true
set -g @dracula-time-format "%m/%d (%a) %H:%M:%S"
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Seoul"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-empty-plugins false
set -g @dracula-continuum-colors "dark_purple white"
set -g status-position top

# Smart pane resizing with awareness of Vim splits.
# See: https://github.com/RyanMillerC/better-vim-tmux-resizer
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Edit values if you use custom resize_count variables
bind-key -n M-H if-shell "$is_vim" "send-keys M-H"  "resize-pane -L 10"
bind-key -n M-J if-shell "$is_vim" "send-keys M-J"  "resize-pane -D 5"
bind-key -n M-K if-shell "$is_vim" "send-keys M-K"  "resize-pane -U 5"
bind-key -n M-L if-shell "$is_vim" "send-keys M-L"  "resize-pane -R 10"

bind-key -T copy-mode-vi M-H resize-pane -L 10
bind-key -T copy-mode-vi M-J resize-pane -D 5
bind-key -T copy-mode-vi M-K resize-pane -U 5
bind-key -T copy-mode-vi M-L resize-pane -R 10



run '~/.tmux/plugins/tpm/tpm'
